name: continuous-deployment

on:
  pull_request:
    types: closed
    branches:
      - main
    # paths:
    #   - main.py

env:
  MERGE_SHA: ${{ github.sha }}
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  HOST_ARTIFACT_REGISTRY: |
    ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY }}
  IMAGE_NAME: ${{ github.event.pull_request.base.repo.name }}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - id: auth
        name: GCP Authentication
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Configure docker
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      - name: Change tag and push
        run: |
          docker pull $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$COMMIT_SHA
          docker tag $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$COMMIT_SHA $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$MERGE_SHA
          docker tag $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$COMMIT_SHA $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:latest
          docker push $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$MERGE_SHA
          docker push $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:latest
          docker rmi $HOST_ARTIFACT_REGISTRY/$IMAGE_NAME:$COMMIT_SHA